# Schema for the configuration files of the hbk colissimo chrono module.
hbkcolissimochrono.settings:
  type: config_object
  label: 'hbk colissimo chrono settings'
  mapping:
    example:
      type: string
      label: 'Example'
